spring:
  profiles:
    active: cloud

---

spring:
  profiles: cloud
  cloud:
    config:
      discovery:
        enabled: true

server:
  port: 8761
  
eureka:
  instance:
    hostname: eureka-server
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://eureka-server:8761/eureka