spring:
  profiles:
    active: cloud

---

spring:
  profiles: cloud
  application:
    name: microservice

server:
  port: 9090

eureka:
  client:
    serviceUrl: 
      defaultZone: http://eureka:8761/eureka/

logging:
  file: /tmp/microservice.log

management:
  security:
    enabled: false
    
ms:
  label: Sample Microservice
  version: 1.0