spring: 
  application:
    name: microservice

server:
  port: 9090

#eureka:
#  client:
#    serviceUrl:
#      defaultZone: http://eureka:8761/eureka/

#ribbon:
#  eureka:
#    enabled: true

logging:
  file: /tmp/microservice.log

management:
  security:
    enabled: false
